---
title: "Statistik Diagramme"
author: "Sanja Perovic"
date: "8/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(readr)
library(ggplot2)
library(tidyverse)
df <- read_csv("responses.csv")
```

```{r}
glimpse(df)
```

```{r}
df <- drop_na(df)
```

```{r}
df$Smoking <- as.factor(df$Smoking)
levels(df$Smoking)
```

```{r}
df$Gender <- as.factor(df$Gender)
levels(df$Gender)
```

# Histogramme
## Histogramm 1
```{r}
ggplot(df, aes( x = Age)) +
                geom_histogram(binwidth = 5, color= "black", fill = "lightblue") +
                  labs(title="Alter der Teilnehmer",
                       subtitle="Histogramm")+
                  xlab("Alter der Teilnehmer") +
                  ylab("Anzahl der Teilnehmer")
  
```

# Barplots
## Barplot 1
```{r}
ggplot(df, aes( x = Loneliness)) +
  geom_bar(fill = "darkred", color = "black") +
  labs(title="Einsamkeit der Teilnehmer",
       subtitle="Barplot")+
  xlab("Einsamkeit der Teilnehmer") +
  ylab("Anzahl der Teilnehmer")
```

# Faceted Barplot
## Facedet Barplot 1
```{r}
ggplot(df, aes( x = Gender)) + # Entfernung von fill
  geom_bar( position = "dodge", fill= "darkblue") +
  facet_wrap(~ df$`Active sport` ) + # Getrennte Darstellung der Ausprägungen 
  ggtitle("Aktiv sportlich tätig", "1 (wenig) 5(sehr)") +
  xlab("Geschlecht der Teilnehmer") +
  ylab("Anzahl der Teilnehmer") +
  theme_classic() +
  theme(legend.title = element_blank()) +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust=  1))
```
# Stacked Barplot
## Stacked Barplot 1
```{r}
ggplot(df, aes(   x = Gender, 
                 fill = Punctuality)) +
  geom_bar( position = "fill") + # Änderung der Darstellung
  ggtitle("Pünktlichkeit", "Überblick") +
  xlab(" Geschlecht der Teilnehmer") +
  ylab("Anzahl der Antworten") +
  theme_classic() +
  scale_fill_brewer(palette = "Greens") +
  theme(legend.title = element_blank())
```
# Side by Side Barplot
## Side by Side Barplot 1
```{r}
ggplot(df, aes(   x = Age, 
                 fill = Smoking)) +
  geom_bar( position = "dodge") +
  ggtitle("Zusammenhand Alter & Rauchen", "Befragte zwischen 15-35 Jahren") +
  xlab("Alter der Teilnehmer") +
  ylab("Anzahl der Teilnehmer") +
  theme_classic() +
  scale_fill_brewer(palette = "Reds") +
  theme(legend.title = element_blank())
```

# Boxplot
## Boxplot 1
```{r}
ggplot(df, aes( x = Education, # kategoriale Variable
                  y= df$`Happiness in life`)) + # numerische Variable
  geom_boxplot(fill ="pink", position = "dodge") +
  ggtitle("Zusammenhand Bildung und Glücklischsein", "unglücklich (1) bis sehr glücklich (5)") +
  xlab("Schulbildung") +
  ylab("Skala Glücklichsein") +
  theme_classic()
```

# Faceted Histogramm
## Faceted Histogramm 1
```{r}
ggplot(df, aes( x = God)) +
  geom_histogram(fill ="pink", binwidth = 1, color = "black")+
  facet_wrap(~Lying) +
  ggtitle("Zusammenhand Glaube und Ehrlichkeit", "Wie viel lügen Gläubige") +
  xlab("Glaube an Gott") +
  ylab("Anzahl Teilnehmer, die schon gelogen haben") +
  theme_classic()
```

# Scatterplot
## Scatterplot 1
```{r}
ggplot(df, aes( x= Height,
                y= Weight)) +
         geom_point( color ="purple") +
  ggtitle("Zusammenhand Größe und Gewicht", "Größe in cm und Gewicht in kg") +
  xlab("Größe") +
  ylab("Gewicht") +
  theme_classic()
```

# Line Graph
## Line Graph 1
```{r}
df <-     # Speichern des Ergebnisses
  df %>%  # Nutzung der Daten aus wage
  group_by(Age) %>%  # Gruppierung der Daten nach Alter
  mutate(mean_Gardening = mean(Gardening, na.rm = TRUE)) %>%  # Berechnung Mittelwert pro Gruppe und Erzeugung der neuen Variable mean_wage
  ungroup() # Gruppierung wieder aufheben


ggplot(df, aes( x = Age,
                y = mean_Gardening)) + 
  geom_line(alpha=0.6, color="deepskyblue4")+
  ggtitle("Gartenarbeit nach Alter der Teilnehmer", "Überblick") +
  xlab("Alter der Teilnehmer") +
  ylab("Gartenarbeit") 
  theme_classic()
```

